use_frameworks!

target 'Marmot-iOS' do
  pod 'Marmot', :path => '../'
  pod 'SnapKit'
  pod 'AnyFormatProtocol'
  pod 'BLFoundation', '0.5.6'
end

target 'Marmot_Example' do
  pod 'Marmot', :path => '../'
  pod 'SnapKit'
end
